/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 17.0.0 -fPIC -O3) */

module add_4bit(a, b, cin, s, cout);
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  input cin;
  wire cin;
  output [3:0] s;
  wire [3:0] s;
  output cout;
  wire cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire [3:0] G;
  wire [3:0] P;
  wire c0;
  wire c1;
  wire c2;
  assign _00_ = P[0] & cin;
  assign c0 = G[0] | _00_;
  assign _01_ = P[1] & G[0];
  assign _16_ = G[1] | _01_;
  assign _02_ = P[1] & P[0];
  assign _03_ = _02_ & cin;
  assign c1 = _16_ | _03_;
  assign _04_ = P[2] & G[1];
  assign _17_ = G[2] | _04_;
  assign _06_ = _05_ & G[0];
  assign _18_ = _17_ | _06_;
  assign _05_ = P[2] & P[1];
  assign _07_ = _05_ & P[0];
  assign _08_ = _07_ & cin;
  assign c2 = _18_ | _08_;
  assign _09_ = P[3] & G[2];
  assign _19_ = G[3] | _09_;
  assign _11_ = _10_ & G[1];
  assign _20_ = _19_ | _11_;
  assign _13_ = _12_ & G[0];
  assign _21_ = _20_ | _13_;
  assign _10_ = P[3] & P[2];
  assign _12_ = _10_ & P[1];
  assign _14_ = _12_ & P[0];
  assign _15_ = _14_ & cin;
  assign cout = _21_ | _15_;
  assign s[0] = P[0] ^ cin;
  assign s[1] = P[1] ^ c0;
  assign s[2] = P[2] ^ c1;
  assign s[3] = P[3] ^ c2;
  and_gate4 Cgen (
    .a(a),
    .b(b),
    .y(G)
  );
  exor_gate4 Cprop (
    .a(a),
    .b(b),
    .y(P)
  );
endmodule

module add_8bit(a, b, cin, s, cout);
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  input cin;
  wire cin;
  output [7:0] s;
  wire [7:0] s;
  output cout;
  wire cout;
  wire tempc;
  add_4bit add03 (
    .a(a[3:0]),
    .b(b[3:0]),
    .cin(cin),
    .cout(tempc),
    .s(s[3:0])
  );
  add_4bit add47 (
    .a(a[7:4]),
    .b(b[7:4]),
    .cin(tempc),
    .cout(cout),
    .s(s[7:4])
  );
endmodule

module alu8bit(en, a, b, opcode, out, cout);
  input en;
  wire en;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  input [3:0] opcode;
  wire [3:0] opcode;
  output [7:0] out;
  wire [7:0] out;
  output cout;
  reg cout;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire [1:0] _017_;
  wire [1:0] _018_;
  wire [1:0] _019_;
  wire [1:0] _020_;
  wire [1:0] _021_;
  wire [1:0] _022_;
  wire [1:0] _023_;
  wire [1:0] _024_;
  wire [1:0] _025_;
  wire _026_;
  wire [1:0] _027_;
  wire [1:0] _028_;
  wire [1:0] _029_;
  wire [1:0] _030_;
  wire [1:0] _031_;
  wire [1:0] _032_;
  wire [1:0] _033_;
  wire [1:0] _034_;
  wire [31:0] _035_;
  wire [3:0] _036_;
  wire [7:0] _037_;
  wire [7:0] _038_;
  wire [2:0] _039_;
  wire [0:0] _040_;
  wire [0:0] _041_;
  wire [31:0] _042_;
  wire [7:0] _043_;
  wire [7:0] _044_;
  wire _045_;
  wire _046_;
  wire add_cout;
  wire [7:0] add_out;
  wire [7:0] and_out;
  wire dec_cout;
  wire [7:0] dec_out;
  wire [7:0] exor_out;
  wire inc_cout;
  wire [7:0] inc_out;
  wire [7:0] not_out;
  wire [7:0] or_out;
  wire sub_cout;
  wire [7:0] sub_out;
  always @*
    if (!_009_) cout = _000_;
  assign _010_ = ~opcode[1];
  assign _011_ = ~opcode[0];
  assign _012_ = ~opcode[2];
  assign _009_ = opcode[3] & _008_;
  assign _008_ = opcode[3] & _007_;
  assign _007_ = _004_ & _006_;
  assign _006_ = _001_ & _005_;
  assign _005_ = _002_ & _003_;
  assign _035_[24] = and_out[0] & _036_[3];
  assign _035_[25] = and_out[1] & _036_[3];
  assign _035_[26] = and_out[2] & _036_[3];
  assign _035_[27] = and_out[3] & _036_[3];
  assign _035_[28] = and_out[4] & _036_[3];
  assign _035_[29] = and_out[5] & _036_[3];
  assign _035_[30] = and_out[6] & _036_[3];
  assign _035_[31] = and_out[7] & _036_[3];
  assign _035_[16] = or_out[0] & _036_[2];
  assign _035_[17] = or_out[1] & _036_[2];
  assign _035_[18] = or_out[2] & _036_[2];
  assign _035_[19] = or_out[3] & _036_[2];
  assign _035_[20] = or_out[4] & _036_[2];
  assign _035_[21] = or_out[5] & _036_[2];
  assign _035_[22] = or_out[6] & _036_[2];
  assign _035_[23] = or_out[7] & _036_[2];
  assign _035_[8] = exor_out[0] & _036_[1];
  assign _035_[9] = exor_out[1] & _036_[1];
  assign _035_[10] = exor_out[2] & _036_[1];
  assign _035_[11] = exor_out[3] & _036_[1];
  assign _035_[12] = exor_out[4] & _036_[1];
  assign _035_[13] = exor_out[5] & _036_[1];
  assign _035_[14] = exor_out[6] & _036_[1];
  assign _035_[15] = exor_out[7] & _036_[1];
  assign _035_[0] = not_out[0] & _036_[0];
  assign _035_[1] = not_out[1] & _036_[0];
  assign _035_[2] = not_out[2] & _036_[0];
  assign _035_[3] = not_out[3] & _036_[0];
  assign _035_[4] = not_out[4] & _036_[0];
  assign _035_[5] = not_out[5] & _036_[0];
  assign _035_[6] = not_out[6] & _036_[0];
  assign _035_[7] = not_out[7] & _036_[0];
  assign _039_[2] = sub_cout & _036_[2];
  assign _039_[1] = inc_cout & _036_[1];
  assign _039_[0] = dec_cout & _036_[0];
  assign _042_[24] = add_out[0] & _036_[3];
  assign _042_[25] = add_out[1] & _036_[3];
  assign _042_[26] = add_out[2] & _036_[3];
  assign _042_[27] = add_out[3] & _036_[3];
  assign _042_[28] = add_out[4] & _036_[3];
  assign _042_[29] = add_out[5] & _036_[3];
  assign _042_[30] = add_out[6] & _036_[3];
  assign _042_[31] = add_out[7] & _036_[3];
  assign _042_[16] = sub_out[0] & _036_[2];
  assign _042_[17] = sub_out[1] & _036_[2];
  assign _042_[18] = sub_out[2] & _036_[2];
  assign _042_[19] = sub_out[3] & _036_[2];
  assign _042_[20] = sub_out[4] & _036_[2];
  assign _042_[21] = sub_out[5] & _036_[2];
  assign _042_[22] = sub_out[6] & _036_[2];
  assign _042_[23] = sub_out[7] & _036_[2];
  assign _042_[8] = inc_out[0] & _036_[1];
  assign _042_[9] = inc_out[1] & _036_[1];
  assign _042_[10] = inc_out[2] & _036_[1];
  assign _042_[11] = inc_out[3] & _036_[1];
  assign _042_[12] = inc_out[4] & _036_[1];
  assign _042_[13] = inc_out[5] & _036_[1];
  assign _042_[14] = inc_out[6] & _036_[1];
  assign _042_[15] = inc_out[7] & _036_[1];
  assign _042_[0] = dec_out[0] & _036_[0];
  assign _042_[1] = dec_out[1] & _036_[0];
  assign _042_[2] = dec_out[2] & _036_[0];
  assign _042_[3] = dec_out[3] & _036_[0];
  assign _042_[4] = dec_out[4] & _036_[0];
  assign _042_[5] = dec_out[5] & _036_[0];
  assign _042_[6] = dec_out[6] & _036_[0];
  assign _042_[7] = dec_out[7] & _036_[0];
  assign _013_ = opcode[0] | opcode[1];
  assign _003_ = _013_ | _012_;
  assign _014_ = _011_ | opcode[1];
  assign _002_ = _014_ | _012_;
  assign _015_ = opcode[0] | _010_;
  assign _001_ = _015_ | _012_;
  assign _016_ = _011_ | _010_;
  assign _004_ = _016_ | _012_;
  assign _017_[0] = _035_[7] | _035_[15];
  assign _017_[1] = _035_[23] | _035_[31];
  assign _038_[7] = _017_[0] | _017_[1];
  assign _018_[0] = _035_[6] | _035_[14];
  assign _018_[1] = _035_[22] | _035_[30];
  assign _038_[6] = _018_[0] | _018_[1];
  assign _019_[0] = _035_[5] | _035_[13];
  assign _019_[1] = _035_[21] | _035_[29];
  assign _038_[5] = _019_[0] | _019_[1];
  assign _020_[0] = _035_[4] | _035_[12];
  assign _020_[1] = _035_[20] | _035_[28];
  assign _038_[4] = _020_[0] | _020_[1];
  assign _021_[0] = _035_[3] | _035_[11];
  assign _021_[1] = _035_[19] | _035_[27];
  assign _038_[3] = _021_[0] | _021_[1];
  assign _022_[0] = _035_[2] | _035_[10];
  assign _022_[1] = _035_[18] | _035_[26];
  assign _038_[2] = _022_[0] | _022_[1];
  assign _023_[0] = _035_[1] | _035_[9];
  assign _023_[1] = _035_[17] | _035_[25];
  assign _038_[1] = _023_[0] | _023_[1];
  assign _024_[0] = _035_[0] | _035_[8];
  assign _024_[1] = _035_[16] | _035_[24];
  assign _038_[0] = _024_[0] | _024_[1];
  assign _025_[1] = _036_[2] | _036_[3];
  assign _045_ = _025_[0] | _025_[1];
  assign _026_ = _039_[0] | _039_[1];
  assign _041_ = _026_ | _039_[2];
  assign _025_[0] = _036_[0] | _036_[1];
  assign _046_ = _025_[0] | _036_[2];
  assign _027_[0] = _042_[7] | _042_[15];
  assign _027_[1] = _042_[23] | _042_[31];
  assign _044_[7] = _027_[0] | _027_[1];
  assign _028_[0] = _042_[6] | _042_[14];
  assign _028_[1] = _042_[22] | _042_[30];
  assign _044_[6] = _028_[0] | _028_[1];
  assign _029_[0] = _042_[5] | _042_[13];
  assign _029_[1] = _042_[21] | _042_[29];
  assign _044_[5] = _029_[0] | _029_[1];
  assign _030_[0] = _042_[4] | _042_[12];
  assign _030_[1] = _042_[20] | _042_[28];
  assign _044_[4] = _030_[0] | _030_[1];
  assign _031_[0] = _042_[3] | _042_[11];
  assign _031_[1] = _042_[19] | _042_[27];
  assign _044_[3] = _031_[0] | _031_[1];
  assign _032_[0] = _042_[2] | _042_[10];
  assign _032_[1] = _042_[18] | _042_[26];
  assign _044_[2] = _032_[0] | _032_[1];
  assign _033_[0] = _042_[1] | _042_[9];
  assign _033_[1] = _042_[17] | _042_[25];
  assign _044_[1] = _033_[0] | _033_[1];
  assign _034_[0] = _042_[0] | _042_[8];
  assign _034_[1] = _042_[16] | _042_[24];
  assign _044_[0] = _034_[0] | _034_[1];
  assign _036_[0] = ~_003_;
  assign _036_[1] = ~_002_;
  assign _036_[2] = ~_001_;
  assign _036_[3] = ~_004_;
  assign out[0] = opcode[3] ? _043_[0] : _037_[0];
  assign out[1] = opcode[3] ? _043_[1] : _037_[1];
  assign out[2] = opcode[3] ? _043_[2] : _037_[2];
  assign out[3] = opcode[3] ? _043_[3] : _037_[3];
  assign out[4] = opcode[3] ? _043_[4] : _037_[4];
  assign out[5] = opcode[3] ? _043_[5] : _037_[5];
  assign out[6] = opcode[3] ? _043_[6] : _037_[6];
  assign out[7] = opcode[3] ? _043_[7] : _037_[7];
  assign _000_ = opcode[3] ? _040_ : 1'h0;
  assign _037_[0] = _045_ ? _038_[0] : 1'h0;
  assign _037_[1] = _045_ ? _038_[1] : 1'h0;
  assign _037_[2] = _045_ ? _038_[2] : 1'h0;
  assign _037_[3] = _045_ ? _038_[3] : 1'h0;
  assign _037_[4] = _045_ ? _038_[4] : 1'h0;
  assign _037_[5] = _045_ ? _038_[5] : 1'h0;
  assign _037_[6] = _045_ ? _038_[6] : 1'h0;
  assign _037_[7] = _045_ ? _038_[7] : 1'h0;
  assign _040_ = _046_ ? _041_ : add_cout;
  assign _043_[0] = _045_ ? _044_[0] : 1'h0;
  assign _043_[1] = _045_ ? _044_[1] : 1'h0;
  assign _043_[2] = _045_ ? _044_[2] : 1'h0;
  assign _043_[3] = _045_ ? _044_[3] : 1'h0;
  assign _043_[4] = _045_ ? _044_[4] : 1'h0;
  assign _043_[5] = _045_ ? _044_[5] : 1'h0;
  assign _043_[6] = _045_ ? _044_[6] : 1'h0;
  assign _043_[7] = _045_ ? _044_[7] : 1'h0;
  add_8bit add (
    .a(a),
    .b(b),
    .cin(1'h0),
    .cout(add_cout),
    .s(add_out)
  );
  and_gate8 and_gate (
    .a8(a),
    .b8(b),
    .y8(and_out)
  );
  dec_8bit dec (
    .a(a),
    .cout(dec_cout),
    .out(dec_out)
  );
  exor_gate8 exor_gate (
    .a(a),
    .b(b),
    .y(exor_out)
  );
  inc_8bit inc (
    .a(a),
    .cout(inc_cout),
    .out(inc_out)
  );
  not_gate8 not_gate (
    .a8(a),
    .y8(not_out)
  );
  or_gate8 or_gate (
    .a8(a),
    .b8(b),
    .y8(or_out)
  );
  sub_8bit sub (
    .a(a),
    .b(b),
    .cout(sub_cout),
    .out(sub_out)
  );
endmodule

module and_gate4(a, b, y);
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  output [3:0] y;
  wire [3:0] y;
  assign y[0] = a[0] & b[0];
  assign y[1] = a[1] & b[1];
  assign y[2] = a[2] & b[2];
  assign y[3] = a[3] & b[3];
endmodule

module and_gate8(a8, b8, y8);
  input [7:0] a8;
  wire [7:0] a8;
  input [7:0] b8;
  wire [7:0] b8;
  output [7:0] y8;
  wire [7:0] y8;
  and_gate4 a03 (
    .a(a8[3:0]),
    .b(b8[3:0]),
    .y(y8[3:0])
  );
  and_gate4 a47 (
    .a(a8[7:4]),
    .b(b8[7:4]),
    .y(y8[7:4])
  );
endmodule

module dec_8bit(a, out, cout);
  input [7:0] a;
  wire [7:0] a;
  output [7:0] out;
  wire [7:0] out;
  output cout;
  wire cout;
  sub_8bit dec (
    .a(a),
    .b(8'h01),
    .cout(cout),
    .out(out)
  );
endmodule

module exor_gate4(a, b, y);
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  output [3:0] y;
  wire [3:0] y;
  assign y[0] = a[0] ^ b[0];
  assign y[1] = a[1] ^ b[1];
  assign y[2] = a[2] ^ b[2];
  assign y[3] = a[3] ^ b[3];
endmodule

module exor_gate8(a, b, y);
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  output [7:0] y;
  wire [7:0] y;
  exor_gate4 x03 (
    .a(a[3:0]),
    .b(b[3:0]),
    .y(y[3:0])
  );
  exor_gate4 x47 (
    .a(a[7:4]),
    .b(b[7:4]),
    .y(y[7:4])
  );
endmodule

module inc_8bit(a, out, cout);
  input [7:0] a;
  wire [7:0] a;
  output [7:0] out;
  wire [7:0] out;
  output cout;
  wire cout;
  wire [7:0] b;
  wire cin;
  add_8bit inc_byte (
    .a(a),
    .b(8'h00),
    .cin(1'h1),
    .cout(cout),
    .s(out)
  );
  assign b = 8'h00;
  assign cin = 1'h1;
endmodule

module not_gate4(a, y);
  input [3:0] a;
  wire [3:0] a;
  output [3:0] y;
  wire [3:0] y;
  assign y[0] = ~a[0];
  assign y[1] = ~a[1];
  assign y[2] = ~a[2];
  assign y[3] = ~a[3];
endmodule

module not_gate8(a8, y8);
  input [7:0] a8;
  wire [7:0] a8;
  output [7:0] y8;
  wire [7:0] y8;
  not_gate4 n03 (
    .a(a8[3:0]),
    .y(y8[3:0])
  );
  not_gate4 n47 (
    .a(a8[7:4]),
    .y(y8[7:4])
  );
endmodule

module or_gate4(a, b, y);
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  output [3:0] y;
  wire [3:0] y;
  assign y[0] = a[0] | b[0];
  assign y[1] = a[1] | b[1];
  assign y[2] = a[2] | b[2];
  assign y[3] = a[3] | b[3];
endmodule

module or_gate8(a8, b8, y8);
  input [7:0] a8;
  wire [7:0] a8;
  input [7:0] b8;
  wire [7:0] b8;
  output [7:0] y8;
  wire [7:0] y8;
  or_gate4 or03 (
    .a(a8[3:0]),
    .b(b8[3:0]),
    .y(y8[3:0])
  );
  or_gate4 or47 (
    .a(a8[7:4]),
    .b(b8[7:4]),
    .y(y8[7:4])
  );
endmodule

module sub_8bit(a, b, out, cout);
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  output [7:0] out;
  wire [7:0] out;
  output cout;
  wire cout;
  wire [7:0] b_in;
  not_gate8 ones_comp (
    .a8(b),
    .y8(b_in)
  );
  add_8bit sub_out (
    .a(a),
    .b(b_in),
    .cin(1'h1),
    .cout(cout),
    .s(out)
  );
endmodule
